<?php
$children = array (
  'dataobject' => 
  array (
    'group' => 'group',
    'backupmodel' => 'backupmodel',
    'uploads' => 'uploads',
    'imageuploads' => 'imageuploads',
    'livecounter' => 'livecounter',
    'permission' => 'permission',
    'user' => 'user',
  ),
  'dataset' => 
  array (
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'dataobjectset' => 
  array (
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'hasmany_dataobjectset' => 
  array (
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'extension' => 
  array (
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'controllerclassinfo' => 'controllerclassinfo',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'infotextfield' => 'infotextfield',
  ),
  'object' => 
  array (
    'classinfo' => 'classinfo',
    'core' => 'core',
    'dev' => 'dev',
    'dataobject' => 'dataobject',
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'dataset' => 'dataset',
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
    'datavalidator' => 'datavalidator',
    'extension' => 'extension',
    'selectquery' => 'selectquery',
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'admin' => 'admin',
    'adminredirectcontroller' => 'adminredirectcontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'imageresize' => 'imageresize',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'controller' => 'controller',
    'controllerclassinfo' => 'controllerclassinfo',
    'convert' => 'convert',
    'dbfield' => 'dbfield',
    'varchar' => 'varchar',
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
    'checkboxsqlfield' => 'checkboxsqlfield',
    'switchsqlfield' => 'switchsqlfield',
    'timezone' => 'timezone',
    'datesqlfield' => 'datesqlfield',
    'imagesqlfield' => 'imagesqlfield',
    'selectsqlfield' => 'selectsqlfield',
    'radiossqlfield' => 'radiossqlfield',
    'i18n' => 'i18n',
    'addcontent' => 'addcontent',
    'group' => 'group',
    'groupcontroller' => 'groupcontroller',
    'request' => 'request',
    'requesthandler' => 'requesthandler',
    'resources' => 'resources',
    'viewaccessabledata' => 'viewaccessabledata',
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'form' => 'form',
    'externalform' => 'externalform',
    'formstate' => 'formstate',
    'formaction' => 'formaction',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'formfield' => 'formfield',
    'formvalidator' => 'formvalidator',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'requestform' => 'requestform',
    'requiredfields' => 'requiredfields',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'infotextfield' => 'infotextfield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefieldconfig' => 'tablefieldconfig',
    'tablefieldconfig_base' => 'tablefieldconfig_base',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
    'gfs' => 'gfs',
    'gfs_package_installer' => 'gfs_package_installer',
    'gfs_package_creator' => 'gfs_package_creator',
    'ajaxlink' => 'ajaxlink',
    'ajaxresponse' => 'ajaxresponse',
    'javascriptresponse' => 'javascriptresponse',
    'dialog' => 'dialog',
    'restfulserver' => 'restfulserver',
    'arraylib' => 'arraylib',
    'backup' => 'backup',
    'backupadmin' => 'backupadmin',
    'backupmodel' => 'backupmodel',
    'cacher' => 'cacher',
    'pagelinkscontroller' => 'pagelinkscontroller',
    'cookies' => 'cookies',
    'cssmin' => 'cssmin',
    'csv' => 'csv',
    'filesystem' => 'filesystem',
    'uploads' => 'uploads',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploads' => 'imageuploads',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'gd' => 'gd',
    'image' => 'image',
    'rootimage' => 'rootimage',
    'htmlnode' => 'htmlnode',
    'httpresponse' => 'httpresponse',
    'htmlparser' => 'htmlparser',
    'rawheaders' => 'rawheaders',
    'gloader' => 'gloader',
    'livecounter' => 'livecounter',
    'livecountercontroller' => 'livecountercontroller',
    'mail' => 'mail',
    'sql' => 'sql',
    'stringlib' => 'stringlib',
    'tabs' => 'tabs',
    'template' => 'template',
    'tpl' => 'tpl',
    'tplcaller' => 'tplcaller',
    'tplcacher' => 'tplcacher',
    'bbcode' => 'bbcode',
    'text' => 'text',
    'texttransformer' => 'texttransformer',
    'jsmin' => 'jsmin',
    'fastjson' => 'fastjson',
    'cfbinarypropertylist' => 'cfbinarypropertylist',
    'cfpropertylist' => 'cfpropertylist',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'permission' => 'permission',
    'hash' => 'hash',
    'md5hash' => 'md5hash',
    'gomahash' => 'gomahash',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'user' => 'user',
    'member' => 'member',
    'profilecontroller' => 'profilecontroller',
    'registerextension' => 'registerextension',
    'treeserver' => 'treeserver',
    'frontedcontroller' => 'frontedcontroller',
    'homepagecontroller' => 'homepagecontroller',
    'installcontroller' => 'installcontroller',
  ),
  'adminitem' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'backupadmin' => 'backupadmin',
  ),
  'admincontroller' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'backupadmin' => 'backupadmin',
  ),
  'tableview' => 
  array (
    'sortabletableview' => 'sortabletableview',
    'backupadmin' => 'backupadmin',
  ),
  'controllerextension' => 
  array (
    'lost_passwordextension' => 'lost_passwordextension',
    'registerextension' => 'registerextension',
  ),
  'controller' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'groupcontroller' => 'groupcontroller',
    'backupadmin' => 'backupadmin',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'livecountercontroller' => 'livecountercontroller',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'registerextension' => 'registerextension',
  ),
  'dbfield' => 
  array (
    'varchar' => 'varchar',
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
    'checkboxsqlfield' => 'checkboxsqlfield',
    'switchsqlfield' => 'switchsqlfield',
    'timezone' => 'timezone',
    'datesqlfield' => 'datesqlfield',
    'imagesqlfield' => 'imagesqlfield',
  ),
  'varchar' => 
  array (
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
  ),
  'requesthandler' => 
  array (
    'dev' => 'dev',
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'adminredirectcontroller' => 'adminredirectcontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'imageresize' => 'imageresize',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'controller' => 'controller',
    'groupcontroller' => 'groupcontroller',
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'externalform' => 'externalform',
    'formaction' => 'formaction',
    'formfield' => 'formfield',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
    'ajaxlink' => 'ajaxlink',
    'restfulserver' => 'restfulserver',
    'backupadmin' => 'backupadmin',
    'pagelinkscontroller' => 'pagelinkscontroller',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'livecountercontroller' => 'livecountercontroller',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'profilecontroller' => 'profilecontroller',
    'registerextension' => 'registerextension',
    'treeserver' => 'treeserver',
    'frontedcontroller' => 'frontedcontroller',
    'homepagecontroller' => 'homepagecontroller',
    'installcontroller' => 'installcontroller',
  ),
  'viewaccessabledata' => 
  array (
    'dataobject' => 'dataobject',
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'dataset' => 'dataset',
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
    'extension' => 'extension',
    'admin' => 'admin',
    'controllerclassinfo' => 'controllerclassinfo',
    'group' => 'group',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'infotextfield' => 'infotextfield',
    'backupmodel' => 'backupmodel',
    'uploads' => 'uploads',
    'imageuploads' => 'imageuploads',
    'rawheaders' => 'rawheaders',
    'livecounter' => 'livecounter',
    'permission' => 'permission',
    'user' => 'user',
  ),
  'clusterformfield' => 
  array (
    'permissionfield' => 'permissionfield',
  ),
  'dropdown' => 
  array (
    'hasonedropdown' => 'hasonedropdown',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'singleselectdropdown' => 'singleselectdropdown',
  ),
  'fieldset' => 
  array (
    'tab' => 'tab',
    'hidablefieldset' => 'hidablefieldset',
    'tabset' => 'tabset',
  ),
  'fileupload' => 
  array (
    'imageupload' => 'imageupload',
  ),
  'formaction' => 
  array (
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'htmlaction' => 'htmlaction',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'linkaction' => 'linkaction',
  ),
  'formdecorator' => 
  array (
    'formdisabler' => 'formdisabler',
  ),
  'formfield' => 
  array (
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'formaction' => 'formaction',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
  ),
  'formvalidator' => 
  array (
    'datavalidator' => 'datavalidator',
    'requiredfields' => 'requiredfields',
  ),
  'htmlfield' => 
  array (
    'infofield' => 'infofield',
  ),
  'hiddenfield' => 
  array (
    'timefield' => 'timefield',
  ),
  'multiselectdropdown' => 
  array (
    'manymanydropdown' => 'manymanydropdown',
  ),
  'radiobutton' => 
  array (
    'objectradiobutton' => 'objectradiobutton',
  ),
  'select' => 
  array (
    'langselect' => 'langselect',
  ),
  'singleselectdropdown' => 
  array (
    'hasonedropdown' => 'hasonedropdown',
  ),
  'textarea' => 
  array (
    'bbcodeeditor' => 'bbcodeeditor',
    'htmleditor' => 'htmleditor',
  ),
  'tablefieldconfig' => 
  array (
    'tablefieldconfig_base' => 'tablefieldconfig_base',
  ),
  'g_softwaretype' => 
  array (
    'g_frameworksoftwaretype' => 'g_frameworksoftwaretype',
    'g_appsoftwaretype' => 'g_appsoftwaretype',
    'g_expansionsoftwaretype' => 'g_expansionsoftwaretype',
  ),
  'gfs' => 
  array (
    'gfs_package_installer' => 'gfs_package_installer',
    'gfs_package_creator' => 'gfs_package_creator',
  ),
  'ajaxresponse' => 
  array (
    'dialog' => 'dialog',
  ),
  'javascriptresponse' => 
  array (
    'ajaxresponse' => 'ajaxresponse',
    'dialog' => 'dialog',
  ),
  'uploads' => 
  array (
    'imageuploads' => 'imageuploads',
  ),
  'uploadscontroller' => 
  array (
    'imageuploadscontroller' => 'imageuploadscontroller',
  ),
  'gd' => 
  array (
    'image' => 'image',
    'rootimage' => 'rootimage',
  ),
  'texttransformer' => 
  array (
    'bbcode' => 'bbcode',
  ),
  'cfbinarypropertylist' => 
  array (
    'cfpropertylist' => 'cfpropertylist',
  ),
  'cftype' => 
  array (
    'cfstring' => 'cfstring',
    'cfnumber' => 'cfnumber',
    'cfdate' => 'cfdate',
    'cfboolean' => 'cfboolean',
    'cfdata' => 'cfdata',
    'cfarray' => 'cfarray',
    'cfdictionary' => 'cfdictionary',
  ),
  'hash' => 
  array (
    'md5hash' => 'md5hash',
    'gomahash' => 'gomahash',
  ),
  'frontedcontroller' => 
  array (
    'profilecontroller' => 'profilecontroller',
  ),
  'newsettings' => 
  array (
    'backupsettings' => 'backupsettings',
  ),
  'exception' => 
  array (
    'jsminexception' => 'jsminexception',
    'ioexception' => 'ioexception',
    'plistexception' => 'plistexception',
  ),
);