<?php
$children = array (
  'dataobject' => 
  array (
    'backupsettings' => 'backupsettings',
    'backupmodel' => 'backupmodel',
    'uploads' => 'uploads',
    'imageuploads' => 'imageuploads',
    'livecounter' => 'livecounter',
    'permission' => 'permission',
    'group' => 'group',
    'user' => 'user',
    'cms_filemanager' => 'cms_filemanager',
    'newsettings' => 'newsettings',
    'metasettings' => 'metasettings',
    'templatesettings' => 'templatesettings',
    'phpbox' => 'phpbox',
    'statistics' => 'statistics',
    'boxes' => 'boxes',
    'box' => 'box',
    'login_meinaccount' => 'login_meinaccount',
    'boxpage' => 'boxpage',
    'page' => 'page',
    'pagecomments' => 'pagecomments',
    'virtualpage' => 'virtualpage',
    'articlecategory' => 'articlecategory',
    'article' => 'article',
    'articles' => 'articles',
    'contact' => 'contact',
    'errorpage' => 'errorpage',
    'members' => 'members',
    'phppage' => 'phppage',
    'redirector' => 'redirector',
    'pages' => 'pages',
    'rating' => 'rating',
    'pm' => 'pm',
    'smilies' => 'smilies',
  ),
  'dataobjectextension' => 
  array (
    'pagecommentsdataobjectextension' => 'pagecommentsdataobjectextension',
    'ratingdataobjectextension' => 'ratingdataobjectextension',
    'searchpageextension' => 'searchpageextension',
  ),
  'dataset' => 
  array (
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'dataobjectset' => 
  array (
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'hasmany_dataobjectset' => 
  array (
    'manymany_dataobjectset' => 'manymany_dataobjectset',
  ),
  'extension' => 
  array (
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'controllerclassinfo' => 'controllerclassinfo',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'infotextfield' => 'infotextfield',
    'boxestplextension' => 'boxestplextension',
    'pagecommentsdataobjectextension' => 'pagecommentsdataobjectextension',
    'contenttplextension' => 'contenttplextension',
    'ratingdataobjectextension' => 'ratingdataobjectextension',
    'pmtemplateextension' => 'pmtemplateextension',
    'searchpageextension' => 'searchpageextension',
    'smiliebbcodeextension' => 'smiliebbcodeextension',
  ),
  'object' => 
  array (
    'classinfo' => 'classinfo',
    'core' => 'core',
    'dev' => 'dev',
    'dataobject' => 'dataobject',
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'dataset' => 'dataset',
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
    'datavalidator' => 'datavalidator',
    'extension' => 'extension',
    'selectquery' => 'selectquery',
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'admin' => 'admin',
    'adminredirectcontroller' => 'adminredirectcontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'imageresize' => 'imageresize',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'controller' => 'controller',
    'controllerclassinfo' => 'controllerclassinfo',
    'convert' => 'convert',
    'dbfield' => 'dbfield',
    'varchar' => 'varchar',
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
    'checkboxsqlfield' => 'checkboxsqlfield',
    'switchsqlfield' => 'switchsqlfield',
    'timezone' => 'timezone',
    'datesqlfield' => 'datesqlfield',
    'imagesqlfield' => 'imagesqlfield',
    'selectsqlfield' => 'selectsqlfield',
    'radiossqlfield' => 'radiossqlfield',
    'i18n' => 'i18n',
    'addcontent' => 'addcontent',
    'request' => 'request',
    'requesthandler' => 'requesthandler',
    'resources' => 'resources',
    'viewaccessabledata' => 'viewaccessabledata',
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'form' => 'form',
    'externalform' => 'externalform',
    'formstate' => 'formstate',
    'formaction' => 'formaction',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'formfield' => 'formfield',
    'formvalidator' => 'formvalidator',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'requestform' => 'requestform',
    'requiredfields' => 'requiredfields',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'infotextfield' => 'infotextfield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefieldconfig' => 'tablefieldconfig',
    'tablefieldconfig_base' => 'tablefieldconfig_base',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
    'gfs' => 'gfs',
    'gfs_package_installer' => 'gfs_package_installer',
    'gfs_package_creator' => 'gfs_package_creator',
    'ajaxlink' => 'ajaxlink',
    'ajaxresponse' => 'ajaxresponse',
    'javascriptresponse' => 'javascriptresponse',
    'dialog' => 'dialog',
    'restfulserver' => 'restfulserver',
    'arraylib' => 'arraylib',
    'backup' => 'backup',
    'backupadmin' => 'backupadmin',
    'backupsettings' => 'backupsettings',
    'backupmodel' => 'backupmodel',
    'cacher' => 'cacher',
    'pagelinkscontroller' => 'pagelinkscontroller',
    'cookies' => 'cookies',
    'cssmin' => 'cssmin',
    'csv' => 'csv',
    'filesystem' => 'filesystem',
    'uploads' => 'uploads',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploads' => 'imageuploads',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'gd' => 'gd',
    'image' => 'image',
    'rootimage' => 'rootimage',
    'htmlnode' => 'htmlnode',
    'httpresponse' => 'httpresponse',
    'htmlparser' => 'htmlparser',
    'rawheaders' => 'rawheaders',
    'gloader' => 'gloader',
    'livecounter' => 'livecounter',
    'livecountercontroller' => 'livecountercontroller',
    'mail' => 'mail',
    'sql' => 'sql',
    'stringlib' => 'stringlib',
    'tabs' => 'tabs',
    'template' => 'template',
    'tpl' => 'tpl',
    'tplcaller' => 'tplcaller',
    'tplcacher' => 'tplcacher',
    'bbcode' => 'bbcode',
    'text' => 'text',
    'texttransformer' => 'texttransformer',
    'jsmin' => 'jsmin',
    'fastjson' => 'fastjson',
    'cfbinarypropertylist' => 'cfbinarypropertylist',
    'cfpropertylist' => 'cfpropertylist',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'permission' => 'permission',
    'group' => 'group',
    'groupcontroller' => 'groupcontroller',
    'hash' => 'hash',
    'md5hash' => 'md5hash',
    'gomahash' => 'gomahash',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'user' => 'user',
    'member' => 'member',
    'profilecontroller' => 'profilecontroller',
    'registerextension' => 'registerextension',
    'treeserver' => 'treeserver',
    'contentadmin' => 'contentadmin',
    'settingsadmin' => 'settingsadmin',
    'smilieadmin' => 'smilieadmin',
    'usergroupadmin' => 'usergroupadmin',
    'frontedcontroller' => 'frontedcontroller',
    'sitecontroller' => 'sitecontroller',
    'homepagecontroller' => 'homepagecontroller',
    'cms_filemanager' => 'cms_filemanager',
    'cms_filemanagercontroller' => 'cms_filemanagercontroller',
    'contentcontroller' => 'contentcontroller',
    'newsettings' => 'newsettings',
    'settingscontroller' => 'settingscontroller',
    'metasettings' => 'metasettings',
    'templatesettings' => 'templatesettings',
    'welcomecontroller' => 'welcomecontroller',
    'phpbox' => 'phpbox',
    'statistics' => 'statistics',
    'boxes' => 'boxes',
    'boxescontroller' => 'boxescontroller',
    'box' => 'box',
    'boxcontroller' => 'boxcontroller',
    'login_meinaccount' => 'login_meinaccount',
    'boxestplextension' => 'boxestplextension',
    'boxpage' => 'boxpage',
    'boxpagecontroller' => 'boxpagecontroller',
    'page' => 'page',
    'pagecontroller' => 'pagecontroller',
    'pagecomments' => 'pagecomments',
    'pagecommentscontroller' => 'pagecommentscontroller',
    'pagecommentsdataobjectextension' => 'pagecommentsdataobjectextension',
    'pagecommentscontrollerextension' => 'pagecommentscontrollerextension',
    'virtualpage' => 'virtualpage',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategory' => 'articlecategory',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'article' => 'article',
    'articlecontroller' => 'articlecontroller',
    'articles' => 'articles',
    'articlescontroller' => 'articlescontroller',
    'contact' => 'contact',
    'contactcontroller' => 'contactcontroller',
    'errorpage' => 'errorpage',
    'errorpagecontroller' => 'errorpagecontroller',
    'members' => 'members',
    'memberscontroller' => 'memberscontroller',
    'phppage' => 'phppage',
    'phppagecontroller' => 'phppagecontroller',
    'redirector' => 'redirector',
    'redirectorcontroller' => 'redirectorcontroller',
    'pages' => 'pages',
    'contenttplextension' => 'contenttplextension',
    'rating' => 'rating',
    'ratingcontroller' => 'ratingcontroller',
    'ratingdataobjectextension' => 'ratingdataobjectextension',
    'pm' => 'pm',
    'pmcontroller' => 'pmcontroller',
    'pmprofileextension' => 'pmprofileextension',
    'pmtemplateextension' => 'pmtemplateextension',
    'searchcontroller' => 'searchcontroller',
    'searchpageextension' => 'searchpageextension',
    'smilies' => 'smilies',
    'smiliebbcodeextension' => 'smiliebbcodeextension',
  ),
  'adminitem' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'backupadmin' => 'backupadmin',
    'contentadmin' => 'contentadmin',
    'settingsadmin' => 'settingsadmin',
    'smilieadmin' => 'smilieadmin',
    'usergroupadmin' => 'usergroupadmin',
  ),
  'admincontroller' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'backupadmin' => 'backupadmin',
    'contentadmin' => 'contentadmin',
    'settingsadmin' => 'settingsadmin',
    'smilieadmin' => 'smilieadmin',
    'usergroupadmin' => 'usergroupadmin',
  ),
  'leftandmain' => 
  array (
    'contentadmin' => 'contentadmin',
    'usergroupadmin' => 'usergroupadmin',
  ),
  'tableview' => 
  array (
    'sortabletableview' => 'sortabletableview',
    'backupadmin' => 'backupadmin',
    'smilieadmin' => 'smilieadmin',
  ),
  'controllerextension' => 
  array (
    'lost_passwordextension' => 'lost_passwordextension',
    'registerextension' => 'registerextension',
    'pagecommentscontrollerextension' => 'pagecommentscontrollerextension',
    'pmprofileextension' => 'pmprofileextension',
  ),
  'controller' => 
  array (
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'backupadmin' => 'backupadmin',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'gloader' => 'gloader',
    'livecountercontroller' => 'livecountercontroller',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'groupcontroller' => 'groupcontroller',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'profilecontroller' => 'profilecontroller',
    'registerextension' => 'registerextension',
    'contentadmin' => 'contentadmin',
    'settingsadmin' => 'settingsadmin',
    'smilieadmin' => 'smilieadmin',
    'usergroupadmin' => 'usergroupadmin',
    'frontedcontroller' => 'frontedcontroller',
    'sitecontroller' => 'sitecontroller',
    'homepagecontroller' => 'homepagecontroller',
    'cms_filemanagercontroller' => 'cms_filemanagercontroller',
    'contentcontroller' => 'contentcontroller',
    'settingscontroller' => 'settingscontroller',
    'welcomecontroller' => 'welcomecontroller',
    'boxescontroller' => 'boxescontroller',
    'boxcontroller' => 'boxcontroller',
    'boxpagecontroller' => 'boxpagecontroller',
    'pagecontroller' => 'pagecontroller',
    'pagecommentscontroller' => 'pagecommentscontroller',
    'pagecommentscontrollerextension' => 'pagecommentscontrollerextension',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'articlecontroller' => 'articlecontroller',
    'articlescontroller' => 'articlescontroller',
    'contactcontroller' => 'contactcontroller',
    'errorpagecontroller' => 'errorpagecontroller',
    'memberscontroller' => 'memberscontroller',
    'phppagecontroller' => 'phppagecontroller',
    'redirectorcontroller' => 'redirectorcontroller',
    'ratingcontroller' => 'ratingcontroller',
    'pmcontroller' => 'pmcontroller',
    'pmprofileextension' => 'pmprofileextension',
    'searchcontroller' => 'searchcontroller',
  ),
  'dbfield' => 
  array (
    'varchar' => 'varchar',
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
    'checkboxsqlfield' => 'checkboxsqlfield',
    'switchsqlfield' => 'switchsqlfield',
    'timezone' => 'timezone',
    'datesqlfield' => 'datesqlfield',
    'imagesqlfield' => 'imagesqlfield',
  ),
  'varchar' => 
  array (
    'textsqlfield' => 'textsqlfield',
    'intsqlfield' => 'intsqlfield',
  ),
  'requesthandler' => 
  array (
    'dev' => 'dev',
    'columnedadmin' => 'columnedadmin',
    'updatecontroller' => 'updatecontroller',
    'adminitem' => 'adminitem',
    'admincontroller' => 'admincontroller',
    'adminredirectcontroller' => 'adminredirectcontroller',
    'leftandmain' => 'leftandmain',
    'sortabletableview' => 'sortabletableview',
    'tableview' => 'tableview',
    'useradmin' => 'useradmin',
    'imageresize' => 'imageresize',
    'systemcontroller' => 'systemcontroller',
    'controllerextension' => 'controllerextension',
    'controller' => 'controller',
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'externalform' => 'externalform',
    'formaction' => 'formaction',
    'formfield' => 'formfield',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
    'ajaxlink' => 'ajaxlink',
    'restfulserver' => 'restfulserver',
    'backupadmin' => 'backupadmin',
    'pagelinkscontroller' => 'pagelinkscontroller',
    'uploadscontroller' => 'uploadscontroller',
    'imageuploadscontroller' => 'imageuploadscontroller',
    'uploadcontroller' => 'uploadcontroller',
    'gloader' => 'gloader',
    'livecountercontroller' => 'livecountercontroller',
    'versionsviewcontroller' => 'versionsviewcontroller',
    'groupcontroller' => 'groupcontroller',
    'lost_passwordextension' => 'lost_passwordextension',
    'usercontroller' => 'usercontroller',
    'profilecontroller' => 'profilecontroller',
    'registerextension' => 'registerextension',
    'treeserver' => 'treeserver',
    'contentadmin' => 'contentadmin',
    'settingsadmin' => 'settingsadmin',
    'smilieadmin' => 'smilieadmin',
    'usergroupadmin' => 'usergroupadmin',
    'frontedcontroller' => 'frontedcontroller',
    'sitecontroller' => 'sitecontroller',
    'homepagecontroller' => 'homepagecontroller',
    'cms_filemanagercontroller' => 'cms_filemanagercontroller',
    'contentcontroller' => 'contentcontroller',
    'settingscontroller' => 'settingscontroller',
    'welcomecontroller' => 'welcomecontroller',
    'boxescontroller' => 'boxescontroller',
    'boxcontroller' => 'boxcontroller',
    'boxpagecontroller' => 'boxpagecontroller',
    'pagecontroller' => 'pagecontroller',
    'pagecommentscontroller' => 'pagecommentscontroller',
    'pagecommentscontrollerextension' => 'pagecommentscontrollerextension',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'articlecontroller' => 'articlecontroller',
    'articlescontroller' => 'articlescontroller',
    'contactcontroller' => 'contactcontroller',
    'errorpagecontroller' => 'errorpagecontroller',
    'memberscontroller' => 'memberscontroller',
    'phppagecontroller' => 'phppagecontroller',
    'redirectorcontroller' => 'redirectorcontroller',
    'ratingcontroller' => 'ratingcontroller',
    'pmcontroller' => 'pmcontroller',
    'pmprofileextension' => 'pmprofileextension',
    'searchcontroller' => 'searchcontroller',
  ),
  'viewaccessabledata' => 
  array (
    'dataobject' => 'dataobject',
    'dataobjectextension' => 'dataobjectextension',
    'dataobjectclassinfo' => 'dataobjectclassinfo',
    'dataset' => 'dataset',
    'dataobjectset' => 'dataobjectset',
    'hasmany_dataobjectset' => 'hasmany_dataobjectset',
    'manymany_dataobjectset' => 'manymany_dataobjectset',
    'extension' => 'extension',
    'admin' => 'admin',
    'controllerclassinfo' => 'controllerclassinfo',
    'formdecorator' => 'formdecorator',
    'formdisabler' => 'formdisabler',
    'infotextfield' => 'infotextfield',
    'backupsettings' => 'backupsettings',
    'backupmodel' => 'backupmodel',
    'uploads' => 'uploads',
    'imageuploads' => 'imageuploads',
    'rawheaders' => 'rawheaders',
    'livecounter' => 'livecounter',
    'permission' => 'permission',
    'group' => 'group',
    'user' => 'user',
    'cms_filemanager' => 'cms_filemanager',
    'newsettings' => 'newsettings',
    'metasettings' => 'metasettings',
    'templatesettings' => 'templatesettings',
    'phpbox' => 'phpbox',
    'statistics' => 'statistics',
    'boxes' => 'boxes',
    'box' => 'box',
    'login_meinaccount' => 'login_meinaccount',
    'boxestplextension' => 'boxestplextension',
    'boxpage' => 'boxpage',
    'page' => 'page',
    'pagecomments' => 'pagecomments',
    'pagecommentsdataobjectextension' => 'pagecommentsdataobjectextension',
    'virtualpage' => 'virtualpage',
    'articlecategory' => 'articlecategory',
    'article' => 'article',
    'articles' => 'articles',
    'contact' => 'contact',
    'errorpage' => 'errorpage',
    'members' => 'members',
    'phppage' => 'phppage',
    'redirector' => 'redirector',
    'pages' => 'pages',
    'contenttplextension' => 'contenttplextension',
    'rating' => 'rating',
    'ratingdataobjectextension' => 'ratingdataobjectextension',
    'pm' => 'pm',
    'pmtemplateextension' => 'pmtemplateextension',
    'searchpageextension' => 'searchpageextension',
    'smilies' => 'smilies',
    'smiliebbcodeextension' => 'smiliebbcodeextension',
  ),
  'clusterformfield' => 
  array (
    'permissionfield' => 'permissionfield',
  ),
  'dropdown' => 
  array (
    'hasonedropdown' => 'hasonedropdown',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'singleselectdropdown' => 'singleselectdropdown',
  ),
  'fieldset' => 
  array (
    'tab' => 'tab',
    'hidablefieldset' => 'hidablefieldset',
    'tabset' => 'tabset',
  ),
  'fileupload' => 
  array (
    'imageupload' => 'imageupload',
  ),
  'formaction' => 
  array (
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'htmlaction' => 'htmlaction',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'linkaction' => 'linkaction',
  ),
  'formdecorator' => 
  array (
    'formdisabler' => 'formdisabler',
  ),
  'formfield' => 
  array (
    'ajaxsubmitbutton' => 'ajaxsubmitbutton',
    'autoformfield' => 'autoformfield',
    'bbcodeeditor' => 'bbcodeeditor',
    'clusterformfield' => 'clusterformfield',
    'dropdown' => 'dropdown',
    'email' => 'email',
    'fieldset' => 'fieldset',
    'fileupload' => 'fileupload',
    'fileuploadset' => 'fileuploadset',
    'formaction' => 'formaction',
    'htmlaction' => 'htmlaction',
    'htmleditor' => 'htmleditor',
    'htmlfield' => 'htmlfield',
    'hasonedropdown' => 'hasonedropdown',
    'hiddenfield' => 'hiddenfield',
    'javascriptfield' => 'javascriptfield',
    'manymanydropdown' => 'manymanydropdown',
    'multiselectdropdown' => 'multiselectdropdown',
    'objectradiobutton' => 'objectradiobutton',
    'passwordfield' => 'passwordfield',
    'permissionfield' => 'permissionfield',
    'radiobutton' => 'radiobutton',
    'select' => 'select',
    'singleselectdropdown' => 'singleselectdropdown',
    'tab' => 'tab',
    'textfield' => 'textfield',
    'textarea' => 'textarea',
    'timefield' => 'timefield',
    'ajaxexternalform' => 'ajaxexternalform',
    'button' => 'button',
    'cancelbutton' => 'cancelbutton',
    'captcha' => 'captcha',
    'checkbox' => 'checkbox',
    'hidablefieldset' => 'hidablefieldset',
    'imageupload' => 'imageupload',
    'infofield' => 'infofield',
    'langselect' => 'langselect',
    'linkaction' => 'linkaction',
    'numberfield' => 'numberfield',
    'tablefield' => 'tablefield',
    'tabset' => 'tabset',
  ),
  'formvalidator' => 
  array (
    'datavalidator' => 'datavalidator',
    'requiredfields' => 'requiredfields',
  ),
  'htmlfield' => 
  array (
    'infofield' => 'infofield',
  ),
  'hiddenfield' => 
  array (
    'timefield' => 'timefield',
  ),
  'multiselectdropdown' => 
  array (
    'manymanydropdown' => 'manymanydropdown',
  ),
  'radiobutton' => 
  array (
    'objectradiobutton' => 'objectradiobutton',
  ),
  'select' => 
  array (
    'langselect' => 'langselect',
  ),
  'singleselectdropdown' => 
  array (
    'hasonedropdown' => 'hasonedropdown',
  ),
  'textarea' => 
  array (
    'bbcodeeditor' => 'bbcodeeditor',
    'htmleditor' => 'htmleditor',
  ),
  'tablefieldcomponent' => 
  array (
    'tablefield_htmlprovider' => 'tablefield_htmlprovider',
    'tablefield_datamanipulator' => 'tablefield_datamanipulator',
    'tablefield_columnprovider' => 'tablefield_columnprovider',
    'tablefield_urlhandler' => 'tablefield_urlhandler',
    'tablefield_actionprovider' => 'tablefield_actionprovider',
  ),
  'tablefieldconfig' => 
  array (
    'tablefieldconfig_base' => 'tablefieldconfig_base',
  ),
  'g_softwaretype' => 
  array (
    'g_frameworksoftwaretype' => 'g_frameworksoftwaretype',
    'g_appsoftwaretype' => 'g_appsoftwaretype',
    'g_expansionsoftwaretype' => 'g_expansionsoftwaretype',
  ),
  'gfs' => 
  array (
    'gfs_package_installer' => 'gfs_package_installer',
    'gfs_package_creator' => 'gfs_package_creator',
  ),
  'ajaxresponse' => 
  array (
    'dialog' => 'dialog',
  ),
  'javascriptresponse' => 
  array (
    'ajaxresponse' => 'ajaxresponse',
    'dialog' => 'dialog',
  ),
  'uploads' => 
  array (
    'imageuploads' => 'imageuploads',
  ),
  'uploadscontroller' => 
  array (
    'imageuploadscontroller' => 'imageuploadscontroller',
  ),
  'gd' => 
  array (
    'image' => 'image',
    'rootimage' => 'rootimage',
  ),
  'texttransformer' => 
  array (
    'bbcode' => 'bbcode',
  ),
  'cfbinarypropertylist' => 
  array (
    'cfpropertylist' => 'cfpropertylist',
  ),
  'cftype' => 
  array (
    'cfstring' => 'cfstring',
    'cfnumber' => 'cfnumber',
    'cfdate' => 'cfdate',
    'cfboolean' => 'cfboolean',
    'cfdata' => 'cfdata',
    'cfarray' => 'cfarray',
    'cfdictionary' => 'cfdictionary',
  ),
  'hash' => 
  array (
    'md5hash' => 'md5hash',
    'gomahash' => 'gomahash',
  ),
  'frontedcontroller' => 
  array (
    'profilecontroller' => 'profilecontroller',
    'contentcontroller' => 'contentcontroller',
    'boxescontroller' => 'boxescontroller',
    'boxcontroller' => 'boxcontroller',
    'boxpagecontroller' => 'boxpagecontroller',
    'pagecontroller' => 'pagecontroller',
    'pagecommentscontroller' => 'pagecommentscontroller',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'articlecontroller' => 'articlecontroller',
    'articlescontroller' => 'articlescontroller',
    'contactcontroller' => 'contactcontroller',
    'errorpagecontroller' => 'errorpagecontroller',
    'memberscontroller' => 'memberscontroller',
    'phppagecontroller' => 'phppagecontroller',
    'redirectorcontroller' => 'redirectorcontroller',
    'pmcontroller' => 'pmcontroller',
    'searchcontroller' => 'searchcontroller',
  ),
  'sitecontroller' => 
  array (
    'homepagecontroller' => 'homepagecontroller',
  ),
  'contentcontroller' => 
  array (
    'boxpagecontroller' => 'boxpagecontroller',
    'pagecontroller' => 'pagecontroller',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'articlecontroller' => 'articlecontroller',
    'articlescontroller' => 'articlescontroller',
    'contactcontroller' => 'contactcontroller',
    'errorpagecontroller' => 'errorpagecontroller',
    'memberscontroller' => 'memberscontroller',
    'phppagecontroller' => 'phppagecontroller',
    'redirectorcontroller' => 'redirectorcontroller',
  ),
  'newsettings' => 
  array (
    'backupsettings' => 'backupsettings',
    'metasettings' => 'metasettings',
    'templatesettings' => 'templatesettings',
  ),
  'boxes' => 
  array (
    'phpbox' => 'phpbox',
    'statistics' => 'statistics',
    'box' => 'box',
    'login_meinaccount' => 'login_meinaccount',
  ),
  'boxescontroller' => 
  array (
    'boxcontroller' => 'boxcontroller',
  ),
  'box' => 
  array (
    'phpbox' => 'phpbox',
    'statistics' => 'statistics',
    'login_meinaccount' => 'login_meinaccount',
  ),
  'page' => 
  array (
    'boxpage' => 'boxpage',
    'virtualpage' => 'virtualpage',
    'articlecategory' => 'articlecategory',
    'article' => 'article',
    'articles' => 'articles',
    'contact' => 'contact',
    'errorpage' => 'errorpage',
    'members' => 'members',
    'phppage' => 'phppage',
    'redirector' => 'redirector',
  ),
  'pagecontroller' => 
  array (
    'boxpagecontroller' => 'boxpagecontroller',
    'virtualpagecontroller' => 'virtualpagecontroller',
    'articlecategorycontroller' => 'articlecategorycontroller',
    'articlecontroller' => 'articlecontroller',
    'articlescontroller' => 'articlescontroller',
    'contactcontroller' => 'contactcontroller',
    'errorpagecontroller' => 'errorpagecontroller',
    'memberscontroller' => 'memberscontroller',
    'phppagecontroller' => 'phppagecontroller',
    'redirectorcontroller' => 'redirectorcontroller',
  ),
  'articlecategory' => 
  array (
    'articles' => 'articles',
  ),
  'articlecategorycontroller' => 
  array (
    'articlescontroller' => 'articlescontroller',
  ),
  'pages' => 
  array (
    'boxpage' => 'boxpage',
    'page' => 'page',
    'virtualpage' => 'virtualpage',
    'articlecategory' => 'articlecategory',
    'article' => 'article',
    'articles' => 'articles',
    'contact' => 'contact',
    'errorpage' => 'errorpage',
    'members' => 'members',
    'phppage' => 'phppage',
    'redirector' => 'redirector',
  ),
  'exception' => 
  array (
    'jsminexception' => 'jsminexception',
    'ioexception' => 'ioexception',
    'plistexception' => 'plistexception',
  ),
);